# Site settings
# -------------
baseurl     : "" # the subpath of your site, e.g. /blog/
colour      : primary
language    : nl
host        : 127.0.0.1
port        : 4000

# SEO
# ---
title      : &title NMDAD-I
description: "New Media Design & Development I at Artevelde University College Ghent"
author     : Philippe De Pauw - Waterschoot
tracking_id: "UA-79628300-1"
# url        :
# image      :

# Build settings
# --------------
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
exclude:
  - Gemfile
  - LICENSE
  - README.md